### ISSUE TITLE
Module not found - urllib.packages.six.move

### ISSUE THREAD

**Issue by BenKentzer** [hotgluexyz/tap-netsuite#53]
Hello!

Python Version 3.12.3

Installed Modules:
```
attrs==24.2.0
backoff==1.3.2
certifi==2024.8.30
chardet==3.0.4
decorator==5.1.1
idna==2.8
isodate==0.7.2
jsonpath-ng==1.4.3
jsonschema==2.6.0
lxml==5.3.0
netsuitesdk @ git+https://github.com/hotgluexyz/netsuite-sdk-py.git@e04c1d24d5c0c70afaac181b10098f69c2fcb5a4
platformdirs==4.3.6
ply==3.11
python-dateutil==2.9.0.post0
pytz==2018.4
requests==2.21.0
requests-file==2.1.0
requests-toolbelt==1.0.0
simplejson==3.11.1
singer-python==5.3.1
six==1.17.0
tap-netsuite @ git+https://github.com/hotgluexyz/tap-netsuite.git@8a5252fe959aff063bdd65de114a3381c80ca1bb
urllib3==1.24.3
xmltodict==0.11.0
zeep==4.3.1
```

Problem:
When I try to validate the config, I get an error. I'm using the command: 
`meltano config tap-netsuite test`

The error I get:
```
2024-12-09T11:39:55.012065Z [info     ] The default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.
Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

Plugin configuration is invalid
Catalog discovery failed: command ['/jaywing/clients/test/meltano/smoketest/.meltano/extractors/tap-netsuite/venv/bin/tap-netsuite', '--config', '/jaywing/clients/test/meltano/smoketest/.meltano/run/tap-netsuite/tap.94a41457-7528-497a-8ec9-88f0223e2e9c.config.json', '--discover'] returned 1 with stderr:
 Traceback (most recent call last):
  File "/jaywing/clients/test/meltano/smoketest/.meltano/extractors/tap-netsuite/venv/bin/tap-netsuite", line 5, in <module>
    from tap_netsuite import main
  File "/jaywing/clients/test/meltano/smoketest/.meltano/extractors/tap-netsuite/venv/lib/python3.12/site-packages/tap_netsuite/__init__.py", line 7, in <module>
    import tap_netsuite.netsuite as netsuite
  File "/jaywing/clients/test/meltano/smoketest/.meltano/extractors/tap-netsuite/venv/lib/python3.12/site-packages/tap_netsuite/netsuite/__init__.py", line 2, in <module>
    from .netsuite_connection import ExtendedNetSuiteConnection
  File "/jaywing/clients/test/meltano/smoketest/.meltano/extractors/tap-netsuite/venv/lib/python3.12/site-packages/tap_netsuite/netsuite/netsuite_connection.py", line 1, in <module>
    from netsuitesdk.api.accounts import Accounts
  File "/jaywing/clients/test/meltano/smoketest/.meltano/extractors/tap-netsuite/venv/lib/python3.12/site-packages/netsuitesdk/__init__.py", line 1, in <module>
    from .connection import NetSuiteConnection
  File "/jaywing/clients/test/meltano/smoketest/.meltano/extractors/tap-netsuite/venv/lib/python3.12/site-packages/netsuitesdk/connection.py", line 1, in <module>
    from .api.accounts import Accounts
  File "/jaywing/clients/test/meltano/smoketest/.meltano/extractors/tap-netsuite/venv/lib/python3.12/site-packages/netsuitesdk/api/accounts.py", line 1, in <module>
    from .base import ApiBase
  File "/jaywing/clients/test/meltano/smoketest/.meltano/extractors/tap-netsuite/venv/lib/python3.12/site-packages/netsuitesdk/api/base.py", line 1, in <module>
    import zeep
  File "/jaywing/clients/test/meltano/smoketest/.meltano/extractors/tap-netsuite/venv/lib/python3.12/site-packages/zeep/__init__.py", line 1, in <module>
    from zeep.client import AsyncClient, CachingClient, Client
  File "/jaywing/clients/test/meltano/smoketest/.meltano/extractors/tap-netsuite/venv/lib/python3.12/site-packages/zeep/client.py", line 6, in <module>
    from zeep.transports import AsyncTransport, Transport
  File "/jaywing/clients/test/meltano/smoketest/.meltano/extractors/tap-netsuite/venv/lib/python3.12/site-packages/zeep/transports.py", line 6, in <module>
    import requests
  File "/jaywing/clients/test/meltano/smoketest/.meltano/extractors/tap-netsuite/venv/lib/python3.12/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/jaywing/clients/test/meltano/smoketest/.meltano/extractors/tap-netsuite/venv/lib/python3.12/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/jaywing/clients/test/meltano/smoketest/.meltano/extractors/tap-netsuite/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/jaywing/clients/test/meltano/smoketest/.meltano/extractors/tap-netsuite/venv/lib/python3.12/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'
```

Any ideas / pointers on what's going wrong with this? 

Thanks, 

Ben

**Comment by BenKentzer** [comment]
Early indications are that by upgrading request, and then upgrading urllib3 within the virtual environment that meltano has created for the tap, the connector is now working - at least, it's not throwing the error of a missing module. 
Now it's complaining it can't see the endpoint, but that's a (I assume) NetSuite issue.

Is there any possibility that this could be looked at as a potential change to the required dependencies on the tap?

Thanks

Ben

**Comment by edgarrmondragon** [comment]
In case it helps, I can reproduce with the oneliner

```
uvx --from 'git+https://github.com/hotgluexyz/tap-netsuite' --python 3.12 tap-netsuite --help
```

<details><summary>Details</summary>
<p>

```
Updated https://github.com/hotgluexyz/tap-netsuite (8a5252f)
Updated https://github.com/hotgluexyz/netsuite-sdk-py.git (e04c1d2)
Installed 25 packages in 32ms
Traceback (most recent call last):
  File "/Users/meltano/Library/Caches/uv/archive-v0/8qCcoSZjS89jeMO5m9S4o/bin/tap-netsuite", line 7, in <module>
    from tap_netsuite import main
  File "/Users/meltano/Library/Caches/uv/archive-v0/8qCcoSZjS89jeMO5m9S4o/lib/python3.12/site-packages/tap_netsuite/__init__.py", line 7, in <module>
    import tap_netsuite.netsuite as netsuite
  File "/Users/meltano/Library/Caches/uv/archive-v0/8qCcoSZjS89jeMO5m9S4o/lib/python3.12/site-packages/tap_netsuite/netsuite/__init__.py", line 2, in <module>
    from .netsuite_connection import ExtendedNetSuiteConnection
  File "/Users/meltano/Library/Caches/uv/archive-v0/8qCcoSZjS89jeMO5m9S4o/lib/python3.12/site-packages/tap_netsuite/netsuite/netsuite_connection.py", line 1, in <module>
    from netsuitesdk.api.accounts import Accounts
  File "/Users/meltano/Library/Caches/uv/archive-v0/8qCcoSZjS89jeMO5m9S4o/lib/python3.12/site-packages/netsuitesdk/__init__.py", line 1, in <module>
    from .connection import NetSuiteConnection
  File "/Users/meltano/Library/Caches/uv/archive-v0/8qCcoSZjS89jeMO5m9S4o/lib/python3.12/site-packages/netsuitesdk/connection.py", line 1, in <module>
    from .api.accounts import Accounts
  File "/Users/meltano/Library/Caches/uv/archive-v0/8qCcoSZjS89jeMO5m9S4o/lib/python3.12/site-packages/netsuitesdk/api/accounts.py", line 1, in <module>
    from .base import ApiBase
  File "/Users/meltano/Library/Caches/uv/archive-v0/8qCcoSZjS89jeMO5m9S4o/lib/python3.12/site-packages/netsuitesdk/api/base.py", line 1, in <module>
    import zeep
  File "/Users/meltano/Library/Caches/uv/archive-v0/8qCcoSZjS89jeMO5m9S4o/lib/python3.12/site-packages/zeep/__init__.py", line 1, in <module>
    from zeep.client import AsyncClient, CachingClient, Client
  File "/Users/meltano/Library/Caches/uv/archive-v0/8qCcoSZjS89jeMO5m9S4o/lib/python3.12/site-packages/zeep/client.py", line 6, in <module>
    from zeep.transports import AsyncTransport, Transport
  File "/Users/meltano/Library/Caches/uv/archive-v0/8qCcoSZjS89jeMO5m9S4o/lib/python3.12/site-packages/zeep/transports.py", line 6, in <module>
    import requests
  File "/Users/meltano/Library/Caches/uv/archive-v0/8qCcoSZjS89jeMO5m9S4o/lib/python3.12/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/Users/meltano/Library/Caches/uv/archive-v0/8qCcoSZjS89jeMO5m9S4o/lib/python3.12/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/Users/meltano/Library/Caches/uv/archive-v0/8qCcoSZjS89jeMO5m9S4o/lib/python3.12/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/Users/meltano/Library/Caches/uv/archive-v0/8qCcoSZjS89jeMO5m9S4o/lib/python3.12/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'
```

</p>
</details>

**Comment by francoisauclair911** [comment]
No updates?
